### ISSUE TITLE
Add Event Pictures

### ISSUE THREAD

**Issue by nh602** [Blueprint-Boulder/f23-PortlandIndigenousMarketplace#145]
The style of the event page has a spot for event specific pictures, but there is no backend function for this. I'm thinking of having a photo gallery at the top of the event page.

**Tasks**
* [ ] Create database table for event pictures
* [ ] Create backend routes for adding / removing pictures to an event
* [ ] Update the event page to use event pictures

**Notes**
* Should be able to upload multiple pictures
* Default picture should be selected if no picture is uploaded
* Should be able to select main picture / change order of images
